from datetime import datetime
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.app_setting import AppSetting


PUBLIC_SETTING_KEYS = {
    "app_name",
    "scheduler_timezone",
    "telegram_bot_token",
    "web_username",
    "web_password",
    "backup_enabled",
    "backup_cron",
    "backup_email_to",
    "smtp_host",
    "smtp_port",
    "smtp_username",
    "smtp_password",
    "smtp_from_email",
    "smtp_use_tls",
}


DEFAULT_APP_SETTINGS = {
    "app_name": settings.app_name,
    "scheduler_timezone": settings.scheduler_timezone,
    "telegram_bot_token": settings.telegram_bot_token,
    "web_username": settings.web_username,
    "web_password": settings.web_password,
    "backup_enabled": "false",
    "backup_cron": "0 3 * * *",
    "backup_email_to": "",
    "smtp_host": "",
    "smtp_port": "587",
    "smtp_username": "",
    "smtp_password": "",
    "smtp_from_email": "",
    "smtp_use_tls": "true",
}


class SettingsService:
    @staticmethod
    async def get_all(db: AsyncSession) -> dict[str, str]:
        result = await db.execute(select(AppSetting))
        values = DEFAULT_APP_SETTINGS.copy()
        for row in result.scalars().all():
            values[row.key] = row.value
        return values

    @staticmethod
    async def get(db: AsyncSession, key: str) -> str:
        if key not in PUBLIC_SETTING_KEYS:
            return ""
        row = await db.get(AppSetting, key)
        if row:
            return row.value
        return DEFAULT_APP_SETTINGS.get(key, "")

    @staticmethod
    async def set_many(db: AsyncSession, values: dict[str, str]) -> dict[str, str]:
        clean = {k: str(v) for k, v in values.items() if k in PUBLIC_SETTING_KEYS and v is not None}
        for key, value in clean.items():
            row = await db.get(AppSetting, key)
            if row:
                row.value = value
                row.updated_at = datetime.utcnow()
            else:
                db.add(AppSetting(key=key, value=value, updated_at=datetime.utcnow()))
        await db.commit()
        await SettingsService.write_env_file(db)
        return await SettingsService.get_all(db)

    @staticmethod
    async def is_configured(db: AsyncSession) -> bool:
        values = await SettingsService.get_all(db)
        return bool(values.get("telegram_bot_token")) and values.get("web_password") not in {"", "change_me", "change_me_please"}

    @staticmethod
    async def write_env_file(db: AsyncSession) -> None:
        values = await SettingsService.get_all(db)
        env_map = {
            "APP_NAME": values.get("app_name", ""),
            "APP_HOST": settings.app_host,
            "APP_PORT": str(settings.app_port),
            "APP_DEBUG": str(settings.app_debug).lower(),
            "DATABASE_URL": settings.database_url,
            "TELEGRAM_BOT_TOKEN": values.get("telegram_bot_token", ""),
            "TELEGRAM_POLL_INTERVAL": str(settings.telegram_poll_interval),
            "SCHEDULER_TIMEZONE": values.get("scheduler_timezone", settings.scheduler_timezone),
            "WEB_USERNAME": values.get("web_username", ""),
            "WEB_PASSWORD": values.get("web_password", ""),
        }
        lines = ["# Generated by Smart Notifier web setup"]
        lines.extend(f"{key}={value}" for key, value in env_map.items())
        Path(".env").write_text("\n".join(lines) + "\n", encoding="utf-8")
